# Makefile.in generated by automake 1.15 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Makefile.am by Marshall Whittaker / oxagast


am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/rotor
pkgincludedir = $(includedir)/rotor
pkglibdir = $(libdir)/rotor
pkglibexecdir = $(libexecdir)/rotor
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = rotor$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_rotor_OBJECTS = src/rotor-rotor.$(OBJEXT) \
	src/rotor-rotor-console.$(OBJEXT) \
	src/rotor-rotor-crypt.$(OBJEXT) \
	src/rotor-rotor-extra.$(OBJEXT) src/rotor-rotor-keys.$(OBJEXT) \
	src/rotor-salsa20.$(OBJEXT) src/rotor-shake.$(OBJEXT) \
	zefcrypt/rotor-yescrypt-ref.$(OBJEXT) \
	zefcrypt/rotor-sha256.$(OBJEXT) \
	libntru/src/rotor-encparams.$(OBJEXT) \
	libntru/src/rotor-arith.$(OBJEXT) \
	libntru/src/rotor-hash.$(OBJEXT) \
	libntru/src/rotor-sha2.$(OBJEXT) \
	libntru/src/rotor-sha1.$(OBJEXT) \
	libntru/src/rotor-key.$(OBJEXT) \
	libntru/src/rotor-poly.$(OBJEXT) \
	libntru/src/rotor-rand.$(OBJEXT) \
	libntru/src/rotor-ntru.$(OBJEXT) \
	libntru/src/rotor-idxgen.$(OBJEXT) \
	libntru/src/rotor-bitstring.$(OBJEXT) \
	libntru/src/rotor-nist_ctr_drbg.$(OBJEXT) \
	libntru/src/rotor-rijndael.$(OBJEXT) \
	libntru/src/rotor-mgf.$(OBJEXT) \
	progressbar/src/rotor-progressbar.$(OBJEXT) \
	passwdqc-1.3.1/rotor-passwdqc_parse.$(OBJEXT) \
	passwdqc-1.3.1/rotor-passwdqc_memzero.$(OBJEXT) \
	passwdqc-1.3.1/rotor-concat.$(OBJEXT) \
	passwdqc-1.3.1/rotor-passwdqc_check.$(OBJEXT) \
	passwdqc-1.3.1/rotor-passwdqc_load.$(OBJEXT) \
	passwdqc-1.3.1/rotor-passwdqc_random.$(OBJEXT) \
	passwdqc-1.3.1/rotor-wordset_4k.$(OBJEXT)
rotor_OBJECTS = $(am_rotor_OBJECTS)
rotor_DEPENDENCIES =
rotor_LINK = $(CCLD) $(rotor_CFLAGS) $(CFLAGS) $(rotor_LDFLAGS) \
	$(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(rotor_SOURCES)
DIST_SOURCES = $(rotor_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in compile depcomp install-sh \
	missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/marshall/Code/oxagastrotor/rotor/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/marshall/Code/oxagastrotor/rotor/missing autoconf
AUTOHEADER = ${SHELL} /home/marshall/Code/oxagastrotor/rotor/missing autoheader
AUTOMAKE = ${SHELL} /home/marshall/Code/oxagastrotor/rotor/missing automake-1.15
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"rotor\" -DPACKAGE_TARNAME=\"rotor\" -DPACKAGE_VERSION=\"0.1\" -DPACKAGE_STRING=\"rotor\ 0.1\" -DPACKAGE_BUGREPORT=\"mrn\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DPACKAGE=\"rotor\" -DVERSION=\"0.1\"
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/marshall/Code/oxagastrotor/rotor/missing makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = rotor
PACKAGE_BUGREPORT = mrn
PACKAGE_NAME = rotor
PACKAGE_STRING = rotor 0.1
PACKAGE_TARNAME = rotor
PACKAGE_URL = 
PACKAGE_VERSION = 0.1
PATH_SEPARATOR = :
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0.1
abs_builddir = /home/marshall/Code/oxagastrotor/rotor
abs_srcdir = /home/marshall/Code/oxagastrotor/rotor
abs_top_builddir = /home/marshall/Code/oxagastrotor/rotor
abs_top_srcdir = /home/marshall/Code/oxagastrotor/rotor
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/marshall/Code/oxagastrotor/rotor/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}
#noinst_LIBRARIES = libbz2.a libpasswdqc.a libprogressbar.a libyescrypt.a libntru.a
#libbz2_a_SOURCES = bzlib/*.c bzlib/*.h
#libpasswdqc_a_SOURCES = passwdqc-1.3.1/pwqgen.c passwdqc-1.3.1/passwdqc_memzero.c passwdqc-1.3.1/concat.c passwdqc-1.3.1/passwdqc_check.c passwdqc-1.3.1/passwdqc_load.c passwdqc-1.3.1/passwdqc_parse.c passwdqc-1.3.1/passwdqc_random.c passwdqc-1.3.1/wordset_4k.c
#libprogressbar_a_SOURCES = progressbar/src/*.c progressbar/include/*.h
#libprogressbar_a_LDFLAGS = -Iprogressbar/include
#libyescrypt_a_SOURCES = zefcrypt/yescrypt-best.c zefcrypt/yescrypt-common.c zefcrypt/blake256.c
#libyescrypt_a_LIDADD = -fopenmp
#libntru_a_SOURCES = libntru/src/bitstring.c libntru/src/encparams.c libntru/src/hash.c libntru/src/idxgen.c libntru/src/key.c libntru/src/mgf.c libntru/src/ntru.c libntru/src/poly.c libntru/src/rand.c libntru/src/arith.c libntru/src/sha1.c libntru/src/sha2.c libntru/src/nist_ctr_drbg.c libntru/src/rijndael.c err.h ntru.h
#libntru_a_LIBADD = -lrt
#libskein_a_sources = skein/Atmel_AVR.c  skein/brg_endian.h  skein/brg_types.h  skein/SHA3api_ref.c  skein/SHA3api_ref.h  skein/skein_block.c  skein/skein.c  skein/skein_debug.c  skein/skein_debug.h  skein/skein.h  skein/skein_port.h  skein/skein_rot_search2.c  skein/skein_test.c
rotor_SOURCES = src/rotor.c src/rotor-console.c src/rotor-console.h \
	src/rotor-crypt.c src/rotor-crypt.h src/rotor-extra.c \
	src/rotor-extra.h src/rotor.h src/rotor-keys.c \
	src/rotor-keys.h src/salsa20.c src/salsa20.h src/shake.c \
	src/shake.h libntru/src/ntru.h include/passwdqc.h \
	include/yescrypt.h zefcrypt/yescrypt-common.h \
	zefcrypt/yescrypt-ref.c zefcrypt/sha256.c \
	include/progressbar.h libntru/src/encparams.h \
	libntru/src/encparams.c libntru/src/arith.c \
	libntru/src/arith.h libntru/src/hash.h libntru/src/hash.c \
	libntru/src/sph_sha2.h libntru/src/sha2.c \
	libntru/src/sph_sha1.h libntru/src/sha1.c include/key.h \
	libntru/src/key.c libntru/src/poly.c libntru/src/rand.h \
	libntru/src/rand.c libntru/src/ntru.c libntru/src/idxgen.c \
	libntru/src/bitstring.c libntru/src/bitstring.h \
	libntru/src/nist_ctr_drbg.h libntru/src/nist_ctr_drbg.c \
	libntru/src/nist_aes_rijndael.h libntru/src/rijndael.c \
	libntru/src/rijndael.h libntru/src/mgf.h libntru/src/mgf.c \
	progressbar/src/progressbar.c passwdqc-1.3.1/passwdqc_parse.c \
	passwdqc-1.3.1/passwdqc_memzero.c passwdqc-1.3.1/concat.c \
	passwdqc-1.3.1/passwdqc_check.c passwdqc-1.3.1/passwdqc_load.c \
	passwdqc-1.3.1/passwdqc_random.c passwdqc-1.3.1/wordset_4k.c
rotor_LDADD = -lcrypto -lm -ltermcap -lomp
rotor_CFLAGS = -O2
rotor_LDFLAGS = -Ilibntru/src -L/usr/local/lib -I./ -Iinclude
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/rotor-rotor.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/rotor-rotor-console.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/rotor-rotor-crypt.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/rotor-rotor-extra.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/rotor-rotor-keys.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/rotor-salsa20.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/rotor-shake.$(OBJEXT): src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
zefcrypt/$(am__dirstamp):
	@$(MKDIR_P) zefcrypt
	@: > zefcrypt/$(am__dirstamp)
zefcrypt/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) zefcrypt/$(DEPDIR)
	@: > zefcrypt/$(DEPDIR)/$(am__dirstamp)
zefcrypt/rotor-yescrypt-ref.$(OBJEXT): zefcrypt/$(am__dirstamp) \
	zefcrypt/$(DEPDIR)/$(am__dirstamp)
zefcrypt/rotor-sha256.$(OBJEXT): zefcrypt/$(am__dirstamp) \
	zefcrypt/$(DEPDIR)/$(am__dirstamp)
libntru/src/$(am__dirstamp):
	@$(MKDIR_P) libntru/src
	@: > libntru/src/$(am__dirstamp)
libntru/src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) libntru/src/$(DEPDIR)
	@: > libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-encparams.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-arith.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-hash.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-sha2.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-sha1.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-key.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-poly.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-rand.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-ntru.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-idxgen.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-bitstring.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-nist_ctr_drbg.$(OBJEXT):  \
	libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-rijndael.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
libntru/src/rotor-mgf.$(OBJEXT): libntru/src/$(am__dirstamp) \
	libntru/src/$(DEPDIR)/$(am__dirstamp)
progressbar/src/$(am__dirstamp):
	@$(MKDIR_P) progressbar/src
	@: > progressbar/src/$(am__dirstamp)
progressbar/src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) progressbar/src/$(DEPDIR)
	@: > progressbar/src/$(DEPDIR)/$(am__dirstamp)
progressbar/src/rotor-progressbar.$(OBJEXT):  \
	progressbar/src/$(am__dirstamp) \
	progressbar/src/$(DEPDIR)/$(am__dirstamp)
passwdqc-1.3.1/$(am__dirstamp):
	@$(MKDIR_P) passwdqc-1.3.1
	@: > passwdqc-1.3.1/$(am__dirstamp)
passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) passwdqc-1.3.1/$(DEPDIR)
	@: > passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)
passwdqc-1.3.1/rotor-passwdqc_parse.$(OBJEXT):  \
	passwdqc-1.3.1/$(am__dirstamp) \
	passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)
passwdqc-1.3.1/rotor-passwdqc_memzero.$(OBJEXT):  \
	passwdqc-1.3.1/$(am__dirstamp) \
	passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)
passwdqc-1.3.1/rotor-concat.$(OBJEXT): passwdqc-1.3.1/$(am__dirstamp) \
	passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)
passwdqc-1.3.1/rotor-passwdqc_check.$(OBJEXT):  \
	passwdqc-1.3.1/$(am__dirstamp) \
	passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)
passwdqc-1.3.1/rotor-passwdqc_load.$(OBJEXT):  \
	passwdqc-1.3.1/$(am__dirstamp) \
	passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)
passwdqc-1.3.1/rotor-passwdqc_random.$(OBJEXT):  \
	passwdqc-1.3.1/$(am__dirstamp) \
	passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)
passwdqc-1.3.1/rotor-wordset_4k.$(OBJEXT):  \
	passwdqc-1.3.1/$(am__dirstamp) \
	passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)

rotor$(EXEEXT): $(rotor_OBJECTS) $(rotor_DEPENDENCIES) $(EXTRA_rotor_DEPENDENCIES) 
	@rm -f rotor$(EXEEXT)
	$(AM_V_CCLD)$(rotor_LINK) $(rotor_OBJECTS) $(rotor_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f libntru/src/*.$(OBJEXT)
	-rm -f passwdqc-1.3.1/*.$(OBJEXT)
	-rm -f progressbar/src/*.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)
	-rm -f zefcrypt/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include libntru/src/$(DEPDIR)/rotor-arith.Po
include libntru/src/$(DEPDIR)/rotor-bitstring.Po
include libntru/src/$(DEPDIR)/rotor-encparams.Po
include libntru/src/$(DEPDIR)/rotor-hash.Po
include libntru/src/$(DEPDIR)/rotor-idxgen.Po
include libntru/src/$(DEPDIR)/rotor-key.Po
include libntru/src/$(DEPDIR)/rotor-mgf.Po
include libntru/src/$(DEPDIR)/rotor-nist_ctr_drbg.Po
include libntru/src/$(DEPDIR)/rotor-ntru.Po
include libntru/src/$(DEPDIR)/rotor-poly.Po
include libntru/src/$(DEPDIR)/rotor-rand.Po
include libntru/src/$(DEPDIR)/rotor-rijndael.Po
include libntru/src/$(DEPDIR)/rotor-sha1.Po
include libntru/src/$(DEPDIR)/rotor-sha2.Po
include passwdqc-1.3.1/$(DEPDIR)/rotor-concat.Po
include passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_check.Po
include passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_load.Po
include passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_memzero.Po
include passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_parse.Po
include passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_random.Po
include passwdqc-1.3.1/$(DEPDIR)/rotor-wordset_4k.Po
include progressbar/src/$(DEPDIR)/rotor-progressbar.Po
include src/$(DEPDIR)/rotor-rotor-console.Po
include src/$(DEPDIR)/rotor-rotor-crypt.Po
include src/$(DEPDIR)/rotor-rotor-extra.Po
include src/$(DEPDIR)/rotor-rotor-keys.Po
include src/$(DEPDIR)/rotor-rotor.Po
include src/$(DEPDIR)/rotor-salsa20.Po
include src/$(DEPDIR)/rotor-shake.Po
include zefcrypt/$(DEPDIR)/rotor-sha256.Po
include zefcrypt/$(DEPDIR)/rotor-yescrypt-ref.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

src/rotor-rotor.o: src/rotor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor.o -MD -MP -MF src/$(DEPDIR)/rotor-rotor.Tpo -c -o src/rotor-rotor.o `test -f 'src/rotor.c' || echo '$(srcdir)/'`src/rotor.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor.Tpo src/$(DEPDIR)/rotor-rotor.Po
#	$(AM_V_CC)source='src/rotor.c' object='src/rotor-rotor.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor.o `test -f 'src/rotor.c' || echo '$(srcdir)/'`src/rotor.c

src/rotor-rotor.obj: src/rotor.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor.obj -MD -MP -MF src/$(DEPDIR)/rotor-rotor.Tpo -c -o src/rotor-rotor.obj `if test -f 'src/rotor.c'; then $(CYGPATH_W) 'src/rotor.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor.Tpo src/$(DEPDIR)/rotor-rotor.Po
#	$(AM_V_CC)source='src/rotor.c' object='src/rotor-rotor.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor.obj `if test -f 'src/rotor.c'; then $(CYGPATH_W) 'src/rotor.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor.c'; fi`

src/rotor-rotor-console.o: src/rotor-console.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor-console.o -MD -MP -MF src/$(DEPDIR)/rotor-rotor-console.Tpo -c -o src/rotor-rotor-console.o `test -f 'src/rotor-console.c' || echo '$(srcdir)/'`src/rotor-console.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor-console.Tpo src/$(DEPDIR)/rotor-rotor-console.Po
#	$(AM_V_CC)source='src/rotor-console.c' object='src/rotor-rotor-console.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor-console.o `test -f 'src/rotor-console.c' || echo '$(srcdir)/'`src/rotor-console.c

src/rotor-rotor-console.obj: src/rotor-console.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor-console.obj -MD -MP -MF src/$(DEPDIR)/rotor-rotor-console.Tpo -c -o src/rotor-rotor-console.obj `if test -f 'src/rotor-console.c'; then $(CYGPATH_W) 'src/rotor-console.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor-console.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor-console.Tpo src/$(DEPDIR)/rotor-rotor-console.Po
#	$(AM_V_CC)source='src/rotor-console.c' object='src/rotor-rotor-console.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor-console.obj `if test -f 'src/rotor-console.c'; then $(CYGPATH_W) 'src/rotor-console.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor-console.c'; fi`

src/rotor-rotor-crypt.o: src/rotor-crypt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor-crypt.o -MD -MP -MF src/$(DEPDIR)/rotor-rotor-crypt.Tpo -c -o src/rotor-rotor-crypt.o `test -f 'src/rotor-crypt.c' || echo '$(srcdir)/'`src/rotor-crypt.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor-crypt.Tpo src/$(DEPDIR)/rotor-rotor-crypt.Po
#	$(AM_V_CC)source='src/rotor-crypt.c' object='src/rotor-rotor-crypt.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor-crypt.o `test -f 'src/rotor-crypt.c' || echo '$(srcdir)/'`src/rotor-crypt.c

src/rotor-rotor-crypt.obj: src/rotor-crypt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor-crypt.obj -MD -MP -MF src/$(DEPDIR)/rotor-rotor-crypt.Tpo -c -o src/rotor-rotor-crypt.obj `if test -f 'src/rotor-crypt.c'; then $(CYGPATH_W) 'src/rotor-crypt.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor-crypt.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor-crypt.Tpo src/$(DEPDIR)/rotor-rotor-crypt.Po
#	$(AM_V_CC)source='src/rotor-crypt.c' object='src/rotor-rotor-crypt.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor-crypt.obj `if test -f 'src/rotor-crypt.c'; then $(CYGPATH_W) 'src/rotor-crypt.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor-crypt.c'; fi`

src/rotor-rotor-extra.o: src/rotor-extra.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor-extra.o -MD -MP -MF src/$(DEPDIR)/rotor-rotor-extra.Tpo -c -o src/rotor-rotor-extra.o `test -f 'src/rotor-extra.c' || echo '$(srcdir)/'`src/rotor-extra.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor-extra.Tpo src/$(DEPDIR)/rotor-rotor-extra.Po
#	$(AM_V_CC)source='src/rotor-extra.c' object='src/rotor-rotor-extra.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor-extra.o `test -f 'src/rotor-extra.c' || echo '$(srcdir)/'`src/rotor-extra.c

src/rotor-rotor-extra.obj: src/rotor-extra.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor-extra.obj -MD -MP -MF src/$(DEPDIR)/rotor-rotor-extra.Tpo -c -o src/rotor-rotor-extra.obj `if test -f 'src/rotor-extra.c'; then $(CYGPATH_W) 'src/rotor-extra.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor-extra.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor-extra.Tpo src/$(DEPDIR)/rotor-rotor-extra.Po
#	$(AM_V_CC)source='src/rotor-extra.c' object='src/rotor-rotor-extra.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor-extra.obj `if test -f 'src/rotor-extra.c'; then $(CYGPATH_W) 'src/rotor-extra.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor-extra.c'; fi`

src/rotor-rotor-keys.o: src/rotor-keys.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor-keys.o -MD -MP -MF src/$(DEPDIR)/rotor-rotor-keys.Tpo -c -o src/rotor-rotor-keys.o `test -f 'src/rotor-keys.c' || echo '$(srcdir)/'`src/rotor-keys.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor-keys.Tpo src/$(DEPDIR)/rotor-rotor-keys.Po
#	$(AM_V_CC)source='src/rotor-keys.c' object='src/rotor-rotor-keys.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor-keys.o `test -f 'src/rotor-keys.c' || echo '$(srcdir)/'`src/rotor-keys.c

src/rotor-rotor-keys.obj: src/rotor-keys.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-rotor-keys.obj -MD -MP -MF src/$(DEPDIR)/rotor-rotor-keys.Tpo -c -o src/rotor-rotor-keys.obj `if test -f 'src/rotor-keys.c'; then $(CYGPATH_W) 'src/rotor-keys.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor-keys.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-rotor-keys.Tpo src/$(DEPDIR)/rotor-rotor-keys.Po
#	$(AM_V_CC)source='src/rotor-keys.c' object='src/rotor-rotor-keys.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-rotor-keys.obj `if test -f 'src/rotor-keys.c'; then $(CYGPATH_W) 'src/rotor-keys.c'; else $(CYGPATH_W) '$(srcdir)/src/rotor-keys.c'; fi`

src/rotor-salsa20.o: src/salsa20.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-salsa20.o -MD -MP -MF src/$(DEPDIR)/rotor-salsa20.Tpo -c -o src/rotor-salsa20.o `test -f 'src/salsa20.c' || echo '$(srcdir)/'`src/salsa20.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-salsa20.Tpo src/$(DEPDIR)/rotor-salsa20.Po
#	$(AM_V_CC)source='src/salsa20.c' object='src/rotor-salsa20.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-salsa20.o `test -f 'src/salsa20.c' || echo '$(srcdir)/'`src/salsa20.c

src/rotor-salsa20.obj: src/salsa20.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-salsa20.obj -MD -MP -MF src/$(DEPDIR)/rotor-salsa20.Tpo -c -o src/rotor-salsa20.obj `if test -f 'src/salsa20.c'; then $(CYGPATH_W) 'src/salsa20.c'; else $(CYGPATH_W) '$(srcdir)/src/salsa20.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-salsa20.Tpo src/$(DEPDIR)/rotor-salsa20.Po
#	$(AM_V_CC)source='src/salsa20.c' object='src/rotor-salsa20.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-salsa20.obj `if test -f 'src/salsa20.c'; then $(CYGPATH_W) 'src/salsa20.c'; else $(CYGPATH_W) '$(srcdir)/src/salsa20.c'; fi`

src/rotor-shake.o: src/shake.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-shake.o -MD -MP -MF src/$(DEPDIR)/rotor-shake.Tpo -c -o src/rotor-shake.o `test -f 'src/shake.c' || echo '$(srcdir)/'`src/shake.c
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-shake.Tpo src/$(DEPDIR)/rotor-shake.Po
#	$(AM_V_CC)source='src/shake.c' object='src/rotor-shake.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-shake.o `test -f 'src/shake.c' || echo '$(srcdir)/'`src/shake.c

src/rotor-shake.obj: src/shake.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT src/rotor-shake.obj -MD -MP -MF src/$(DEPDIR)/rotor-shake.Tpo -c -o src/rotor-shake.obj `if test -f 'src/shake.c'; then $(CYGPATH_W) 'src/shake.c'; else $(CYGPATH_W) '$(srcdir)/src/shake.c'; fi`
	$(AM_V_at)$(am__mv) src/$(DEPDIR)/rotor-shake.Tpo src/$(DEPDIR)/rotor-shake.Po
#	$(AM_V_CC)source='src/shake.c' object='src/rotor-shake.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o src/rotor-shake.obj `if test -f 'src/shake.c'; then $(CYGPATH_W) 'src/shake.c'; else $(CYGPATH_W) '$(srcdir)/src/shake.c'; fi`

zefcrypt/rotor-yescrypt-ref.o: zefcrypt/yescrypt-ref.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT zefcrypt/rotor-yescrypt-ref.o -MD -MP -MF zefcrypt/$(DEPDIR)/rotor-yescrypt-ref.Tpo -c -o zefcrypt/rotor-yescrypt-ref.o `test -f 'zefcrypt/yescrypt-ref.c' || echo '$(srcdir)/'`zefcrypt/yescrypt-ref.c
	$(AM_V_at)$(am__mv) zefcrypt/$(DEPDIR)/rotor-yescrypt-ref.Tpo zefcrypt/$(DEPDIR)/rotor-yescrypt-ref.Po
#	$(AM_V_CC)source='zefcrypt/yescrypt-ref.c' object='zefcrypt/rotor-yescrypt-ref.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o zefcrypt/rotor-yescrypt-ref.o `test -f 'zefcrypt/yescrypt-ref.c' || echo '$(srcdir)/'`zefcrypt/yescrypt-ref.c

zefcrypt/rotor-yescrypt-ref.obj: zefcrypt/yescrypt-ref.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT zefcrypt/rotor-yescrypt-ref.obj -MD -MP -MF zefcrypt/$(DEPDIR)/rotor-yescrypt-ref.Tpo -c -o zefcrypt/rotor-yescrypt-ref.obj `if test -f 'zefcrypt/yescrypt-ref.c'; then $(CYGPATH_W) 'zefcrypt/yescrypt-ref.c'; else $(CYGPATH_W) '$(srcdir)/zefcrypt/yescrypt-ref.c'; fi`
	$(AM_V_at)$(am__mv) zefcrypt/$(DEPDIR)/rotor-yescrypt-ref.Tpo zefcrypt/$(DEPDIR)/rotor-yescrypt-ref.Po
#	$(AM_V_CC)source='zefcrypt/yescrypt-ref.c' object='zefcrypt/rotor-yescrypt-ref.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o zefcrypt/rotor-yescrypt-ref.obj `if test -f 'zefcrypt/yescrypt-ref.c'; then $(CYGPATH_W) 'zefcrypt/yescrypt-ref.c'; else $(CYGPATH_W) '$(srcdir)/zefcrypt/yescrypt-ref.c'; fi`

zefcrypt/rotor-sha256.o: zefcrypt/sha256.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT zefcrypt/rotor-sha256.o -MD -MP -MF zefcrypt/$(DEPDIR)/rotor-sha256.Tpo -c -o zefcrypt/rotor-sha256.o `test -f 'zefcrypt/sha256.c' || echo '$(srcdir)/'`zefcrypt/sha256.c
	$(AM_V_at)$(am__mv) zefcrypt/$(DEPDIR)/rotor-sha256.Tpo zefcrypt/$(DEPDIR)/rotor-sha256.Po
#	$(AM_V_CC)source='zefcrypt/sha256.c' object='zefcrypt/rotor-sha256.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o zefcrypt/rotor-sha256.o `test -f 'zefcrypt/sha256.c' || echo '$(srcdir)/'`zefcrypt/sha256.c

zefcrypt/rotor-sha256.obj: zefcrypt/sha256.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT zefcrypt/rotor-sha256.obj -MD -MP -MF zefcrypt/$(DEPDIR)/rotor-sha256.Tpo -c -o zefcrypt/rotor-sha256.obj `if test -f 'zefcrypt/sha256.c'; then $(CYGPATH_W) 'zefcrypt/sha256.c'; else $(CYGPATH_W) '$(srcdir)/zefcrypt/sha256.c'; fi`
	$(AM_V_at)$(am__mv) zefcrypt/$(DEPDIR)/rotor-sha256.Tpo zefcrypt/$(DEPDIR)/rotor-sha256.Po
#	$(AM_V_CC)source='zefcrypt/sha256.c' object='zefcrypt/rotor-sha256.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o zefcrypt/rotor-sha256.obj `if test -f 'zefcrypt/sha256.c'; then $(CYGPATH_W) 'zefcrypt/sha256.c'; else $(CYGPATH_W) '$(srcdir)/zefcrypt/sha256.c'; fi`

libntru/src/rotor-encparams.o: libntru/src/encparams.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-encparams.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-encparams.Tpo -c -o libntru/src/rotor-encparams.o `test -f 'libntru/src/encparams.c' || echo '$(srcdir)/'`libntru/src/encparams.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-encparams.Tpo libntru/src/$(DEPDIR)/rotor-encparams.Po
#	$(AM_V_CC)source='libntru/src/encparams.c' object='libntru/src/rotor-encparams.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-encparams.o `test -f 'libntru/src/encparams.c' || echo '$(srcdir)/'`libntru/src/encparams.c

libntru/src/rotor-encparams.obj: libntru/src/encparams.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-encparams.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-encparams.Tpo -c -o libntru/src/rotor-encparams.obj `if test -f 'libntru/src/encparams.c'; then $(CYGPATH_W) 'libntru/src/encparams.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/encparams.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-encparams.Tpo libntru/src/$(DEPDIR)/rotor-encparams.Po
#	$(AM_V_CC)source='libntru/src/encparams.c' object='libntru/src/rotor-encparams.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-encparams.obj `if test -f 'libntru/src/encparams.c'; then $(CYGPATH_W) 'libntru/src/encparams.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/encparams.c'; fi`

libntru/src/rotor-arith.o: libntru/src/arith.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-arith.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-arith.Tpo -c -o libntru/src/rotor-arith.o `test -f 'libntru/src/arith.c' || echo '$(srcdir)/'`libntru/src/arith.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-arith.Tpo libntru/src/$(DEPDIR)/rotor-arith.Po
#	$(AM_V_CC)source='libntru/src/arith.c' object='libntru/src/rotor-arith.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-arith.o `test -f 'libntru/src/arith.c' || echo '$(srcdir)/'`libntru/src/arith.c

libntru/src/rotor-arith.obj: libntru/src/arith.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-arith.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-arith.Tpo -c -o libntru/src/rotor-arith.obj `if test -f 'libntru/src/arith.c'; then $(CYGPATH_W) 'libntru/src/arith.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/arith.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-arith.Tpo libntru/src/$(DEPDIR)/rotor-arith.Po
#	$(AM_V_CC)source='libntru/src/arith.c' object='libntru/src/rotor-arith.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-arith.obj `if test -f 'libntru/src/arith.c'; then $(CYGPATH_W) 'libntru/src/arith.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/arith.c'; fi`

libntru/src/rotor-hash.o: libntru/src/hash.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-hash.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-hash.Tpo -c -o libntru/src/rotor-hash.o `test -f 'libntru/src/hash.c' || echo '$(srcdir)/'`libntru/src/hash.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-hash.Tpo libntru/src/$(DEPDIR)/rotor-hash.Po
#	$(AM_V_CC)source='libntru/src/hash.c' object='libntru/src/rotor-hash.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-hash.o `test -f 'libntru/src/hash.c' || echo '$(srcdir)/'`libntru/src/hash.c

libntru/src/rotor-hash.obj: libntru/src/hash.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-hash.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-hash.Tpo -c -o libntru/src/rotor-hash.obj `if test -f 'libntru/src/hash.c'; then $(CYGPATH_W) 'libntru/src/hash.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/hash.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-hash.Tpo libntru/src/$(DEPDIR)/rotor-hash.Po
#	$(AM_V_CC)source='libntru/src/hash.c' object='libntru/src/rotor-hash.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-hash.obj `if test -f 'libntru/src/hash.c'; then $(CYGPATH_W) 'libntru/src/hash.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/hash.c'; fi`

libntru/src/rotor-sha2.o: libntru/src/sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-sha2.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-sha2.Tpo -c -o libntru/src/rotor-sha2.o `test -f 'libntru/src/sha2.c' || echo '$(srcdir)/'`libntru/src/sha2.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-sha2.Tpo libntru/src/$(DEPDIR)/rotor-sha2.Po
#	$(AM_V_CC)source='libntru/src/sha2.c' object='libntru/src/rotor-sha2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-sha2.o `test -f 'libntru/src/sha2.c' || echo '$(srcdir)/'`libntru/src/sha2.c

libntru/src/rotor-sha2.obj: libntru/src/sha2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-sha2.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-sha2.Tpo -c -o libntru/src/rotor-sha2.obj `if test -f 'libntru/src/sha2.c'; then $(CYGPATH_W) 'libntru/src/sha2.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/sha2.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-sha2.Tpo libntru/src/$(DEPDIR)/rotor-sha2.Po
#	$(AM_V_CC)source='libntru/src/sha2.c' object='libntru/src/rotor-sha2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-sha2.obj `if test -f 'libntru/src/sha2.c'; then $(CYGPATH_W) 'libntru/src/sha2.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/sha2.c'; fi`

libntru/src/rotor-sha1.o: libntru/src/sha1.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-sha1.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-sha1.Tpo -c -o libntru/src/rotor-sha1.o `test -f 'libntru/src/sha1.c' || echo '$(srcdir)/'`libntru/src/sha1.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-sha1.Tpo libntru/src/$(DEPDIR)/rotor-sha1.Po
#	$(AM_V_CC)source='libntru/src/sha1.c' object='libntru/src/rotor-sha1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-sha1.o `test -f 'libntru/src/sha1.c' || echo '$(srcdir)/'`libntru/src/sha1.c

libntru/src/rotor-sha1.obj: libntru/src/sha1.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-sha1.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-sha1.Tpo -c -o libntru/src/rotor-sha1.obj `if test -f 'libntru/src/sha1.c'; then $(CYGPATH_W) 'libntru/src/sha1.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/sha1.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-sha1.Tpo libntru/src/$(DEPDIR)/rotor-sha1.Po
#	$(AM_V_CC)source='libntru/src/sha1.c' object='libntru/src/rotor-sha1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-sha1.obj `if test -f 'libntru/src/sha1.c'; then $(CYGPATH_W) 'libntru/src/sha1.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/sha1.c'; fi`

libntru/src/rotor-key.o: libntru/src/key.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-key.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-key.Tpo -c -o libntru/src/rotor-key.o `test -f 'libntru/src/key.c' || echo '$(srcdir)/'`libntru/src/key.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-key.Tpo libntru/src/$(DEPDIR)/rotor-key.Po
#	$(AM_V_CC)source='libntru/src/key.c' object='libntru/src/rotor-key.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-key.o `test -f 'libntru/src/key.c' || echo '$(srcdir)/'`libntru/src/key.c

libntru/src/rotor-key.obj: libntru/src/key.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-key.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-key.Tpo -c -o libntru/src/rotor-key.obj `if test -f 'libntru/src/key.c'; then $(CYGPATH_W) 'libntru/src/key.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/key.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-key.Tpo libntru/src/$(DEPDIR)/rotor-key.Po
#	$(AM_V_CC)source='libntru/src/key.c' object='libntru/src/rotor-key.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-key.obj `if test -f 'libntru/src/key.c'; then $(CYGPATH_W) 'libntru/src/key.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/key.c'; fi`

libntru/src/rotor-poly.o: libntru/src/poly.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-poly.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-poly.Tpo -c -o libntru/src/rotor-poly.o `test -f 'libntru/src/poly.c' || echo '$(srcdir)/'`libntru/src/poly.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-poly.Tpo libntru/src/$(DEPDIR)/rotor-poly.Po
#	$(AM_V_CC)source='libntru/src/poly.c' object='libntru/src/rotor-poly.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-poly.o `test -f 'libntru/src/poly.c' || echo '$(srcdir)/'`libntru/src/poly.c

libntru/src/rotor-poly.obj: libntru/src/poly.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-poly.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-poly.Tpo -c -o libntru/src/rotor-poly.obj `if test -f 'libntru/src/poly.c'; then $(CYGPATH_W) 'libntru/src/poly.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/poly.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-poly.Tpo libntru/src/$(DEPDIR)/rotor-poly.Po
#	$(AM_V_CC)source='libntru/src/poly.c' object='libntru/src/rotor-poly.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-poly.obj `if test -f 'libntru/src/poly.c'; then $(CYGPATH_W) 'libntru/src/poly.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/poly.c'; fi`

libntru/src/rotor-rand.o: libntru/src/rand.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-rand.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-rand.Tpo -c -o libntru/src/rotor-rand.o `test -f 'libntru/src/rand.c' || echo '$(srcdir)/'`libntru/src/rand.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-rand.Tpo libntru/src/$(DEPDIR)/rotor-rand.Po
#	$(AM_V_CC)source='libntru/src/rand.c' object='libntru/src/rotor-rand.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-rand.o `test -f 'libntru/src/rand.c' || echo '$(srcdir)/'`libntru/src/rand.c

libntru/src/rotor-rand.obj: libntru/src/rand.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-rand.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-rand.Tpo -c -o libntru/src/rotor-rand.obj `if test -f 'libntru/src/rand.c'; then $(CYGPATH_W) 'libntru/src/rand.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/rand.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-rand.Tpo libntru/src/$(DEPDIR)/rotor-rand.Po
#	$(AM_V_CC)source='libntru/src/rand.c' object='libntru/src/rotor-rand.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-rand.obj `if test -f 'libntru/src/rand.c'; then $(CYGPATH_W) 'libntru/src/rand.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/rand.c'; fi`

libntru/src/rotor-ntru.o: libntru/src/ntru.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-ntru.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-ntru.Tpo -c -o libntru/src/rotor-ntru.o `test -f 'libntru/src/ntru.c' || echo '$(srcdir)/'`libntru/src/ntru.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-ntru.Tpo libntru/src/$(DEPDIR)/rotor-ntru.Po
#	$(AM_V_CC)source='libntru/src/ntru.c' object='libntru/src/rotor-ntru.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-ntru.o `test -f 'libntru/src/ntru.c' || echo '$(srcdir)/'`libntru/src/ntru.c

libntru/src/rotor-ntru.obj: libntru/src/ntru.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-ntru.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-ntru.Tpo -c -o libntru/src/rotor-ntru.obj `if test -f 'libntru/src/ntru.c'; then $(CYGPATH_W) 'libntru/src/ntru.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/ntru.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-ntru.Tpo libntru/src/$(DEPDIR)/rotor-ntru.Po
#	$(AM_V_CC)source='libntru/src/ntru.c' object='libntru/src/rotor-ntru.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-ntru.obj `if test -f 'libntru/src/ntru.c'; then $(CYGPATH_W) 'libntru/src/ntru.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/ntru.c'; fi`

libntru/src/rotor-idxgen.o: libntru/src/idxgen.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-idxgen.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-idxgen.Tpo -c -o libntru/src/rotor-idxgen.o `test -f 'libntru/src/idxgen.c' || echo '$(srcdir)/'`libntru/src/idxgen.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-idxgen.Tpo libntru/src/$(DEPDIR)/rotor-idxgen.Po
#	$(AM_V_CC)source='libntru/src/idxgen.c' object='libntru/src/rotor-idxgen.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-idxgen.o `test -f 'libntru/src/idxgen.c' || echo '$(srcdir)/'`libntru/src/idxgen.c

libntru/src/rotor-idxgen.obj: libntru/src/idxgen.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-idxgen.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-idxgen.Tpo -c -o libntru/src/rotor-idxgen.obj `if test -f 'libntru/src/idxgen.c'; then $(CYGPATH_W) 'libntru/src/idxgen.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/idxgen.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-idxgen.Tpo libntru/src/$(DEPDIR)/rotor-idxgen.Po
#	$(AM_V_CC)source='libntru/src/idxgen.c' object='libntru/src/rotor-idxgen.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-idxgen.obj `if test -f 'libntru/src/idxgen.c'; then $(CYGPATH_W) 'libntru/src/idxgen.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/idxgen.c'; fi`

libntru/src/rotor-bitstring.o: libntru/src/bitstring.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-bitstring.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-bitstring.Tpo -c -o libntru/src/rotor-bitstring.o `test -f 'libntru/src/bitstring.c' || echo '$(srcdir)/'`libntru/src/bitstring.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-bitstring.Tpo libntru/src/$(DEPDIR)/rotor-bitstring.Po
#	$(AM_V_CC)source='libntru/src/bitstring.c' object='libntru/src/rotor-bitstring.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-bitstring.o `test -f 'libntru/src/bitstring.c' || echo '$(srcdir)/'`libntru/src/bitstring.c

libntru/src/rotor-bitstring.obj: libntru/src/bitstring.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-bitstring.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-bitstring.Tpo -c -o libntru/src/rotor-bitstring.obj `if test -f 'libntru/src/bitstring.c'; then $(CYGPATH_W) 'libntru/src/bitstring.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/bitstring.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-bitstring.Tpo libntru/src/$(DEPDIR)/rotor-bitstring.Po
#	$(AM_V_CC)source='libntru/src/bitstring.c' object='libntru/src/rotor-bitstring.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-bitstring.obj `if test -f 'libntru/src/bitstring.c'; then $(CYGPATH_W) 'libntru/src/bitstring.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/bitstring.c'; fi`

libntru/src/rotor-nist_ctr_drbg.o: libntru/src/nist_ctr_drbg.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-nist_ctr_drbg.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-nist_ctr_drbg.Tpo -c -o libntru/src/rotor-nist_ctr_drbg.o `test -f 'libntru/src/nist_ctr_drbg.c' || echo '$(srcdir)/'`libntru/src/nist_ctr_drbg.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-nist_ctr_drbg.Tpo libntru/src/$(DEPDIR)/rotor-nist_ctr_drbg.Po
#	$(AM_V_CC)source='libntru/src/nist_ctr_drbg.c' object='libntru/src/rotor-nist_ctr_drbg.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-nist_ctr_drbg.o `test -f 'libntru/src/nist_ctr_drbg.c' || echo '$(srcdir)/'`libntru/src/nist_ctr_drbg.c

libntru/src/rotor-nist_ctr_drbg.obj: libntru/src/nist_ctr_drbg.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-nist_ctr_drbg.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-nist_ctr_drbg.Tpo -c -o libntru/src/rotor-nist_ctr_drbg.obj `if test -f 'libntru/src/nist_ctr_drbg.c'; then $(CYGPATH_W) 'libntru/src/nist_ctr_drbg.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/nist_ctr_drbg.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-nist_ctr_drbg.Tpo libntru/src/$(DEPDIR)/rotor-nist_ctr_drbg.Po
#	$(AM_V_CC)source='libntru/src/nist_ctr_drbg.c' object='libntru/src/rotor-nist_ctr_drbg.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-nist_ctr_drbg.obj `if test -f 'libntru/src/nist_ctr_drbg.c'; then $(CYGPATH_W) 'libntru/src/nist_ctr_drbg.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/nist_ctr_drbg.c'; fi`

libntru/src/rotor-rijndael.o: libntru/src/rijndael.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-rijndael.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-rijndael.Tpo -c -o libntru/src/rotor-rijndael.o `test -f 'libntru/src/rijndael.c' || echo '$(srcdir)/'`libntru/src/rijndael.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-rijndael.Tpo libntru/src/$(DEPDIR)/rotor-rijndael.Po
#	$(AM_V_CC)source='libntru/src/rijndael.c' object='libntru/src/rotor-rijndael.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-rijndael.o `test -f 'libntru/src/rijndael.c' || echo '$(srcdir)/'`libntru/src/rijndael.c

libntru/src/rotor-rijndael.obj: libntru/src/rijndael.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-rijndael.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-rijndael.Tpo -c -o libntru/src/rotor-rijndael.obj `if test -f 'libntru/src/rijndael.c'; then $(CYGPATH_W) 'libntru/src/rijndael.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/rijndael.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-rijndael.Tpo libntru/src/$(DEPDIR)/rotor-rijndael.Po
#	$(AM_V_CC)source='libntru/src/rijndael.c' object='libntru/src/rotor-rijndael.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-rijndael.obj `if test -f 'libntru/src/rijndael.c'; then $(CYGPATH_W) 'libntru/src/rijndael.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/rijndael.c'; fi`

libntru/src/rotor-mgf.o: libntru/src/mgf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-mgf.o -MD -MP -MF libntru/src/$(DEPDIR)/rotor-mgf.Tpo -c -o libntru/src/rotor-mgf.o `test -f 'libntru/src/mgf.c' || echo '$(srcdir)/'`libntru/src/mgf.c
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-mgf.Tpo libntru/src/$(DEPDIR)/rotor-mgf.Po
#	$(AM_V_CC)source='libntru/src/mgf.c' object='libntru/src/rotor-mgf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-mgf.o `test -f 'libntru/src/mgf.c' || echo '$(srcdir)/'`libntru/src/mgf.c

libntru/src/rotor-mgf.obj: libntru/src/mgf.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT libntru/src/rotor-mgf.obj -MD -MP -MF libntru/src/$(DEPDIR)/rotor-mgf.Tpo -c -o libntru/src/rotor-mgf.obj `if test -f 'libntru/src/mgf.c'; then $(CYGPATH_W) 'libntru/src/mgf.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/mgf.c'; fi`
	$(AM_V_at)$(am__mv) libntru/src/$(DEPDIR)/rotor-mgf.Tpo libntru/src/$(DEPDIR)/rotor-mgf.Po
#	$(AM_V_CC)source='libntru/src/mgf.c' object='libntru/src/rotor-mgf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o libntru/src/rotor-mgf.obj `if test -f 'libntru/src/mgf.c'; then $(CYGPATH_W) 'libntru/src/mgf.c'; else $(CYGPATH_W) '$(srcdir)/libntru/src/mgf.c'; fi`

progressbar/src/rotor-progressbar.o: progressbar/src/progressbar.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT progressbar/src/rotor-progressbar.o -MD -MP -MF progressbar/src/$(DEPDIR)/rotor-progressbar.Tpo -c -o progressbar/src/rotor-progressbar.o `test -f 'progressbar/src/progressbar.c' || echo '$(srcdir)/'`progressbar/src/progressbar.c
	$(AM_V_at)$(am__mv) progressbar/src/$(DEPDIR)/rotor-progressbar.Tpo progressbar/src/$(DEPDIR)/rotor-progressbar.Po
#	$(AM_V_CC)source='progressbar/src/progressbar.c' object='progressbar/src/rotor-progressbar.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o progressbar/src/rotor-progressbar.o `test -f 'progressbar/src/progressbar.c' || echo '$(srcdir)/'`progressbar/src/progressbar.c

progressbar/src/rotor-progressbar.obj: progressbar/src/progressbar.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT progressbar/src/rotor-progressbar.obj -MD -MP -MF progressbar/src/$(DEPDIR)/rotor-progressbar.Tpo -c -o progressbar/src/rotor-progressbar.obj `if test -f 'progressbar/src/progressbar.c'; then $(CYGPATH_W) 'progressbar/src/progressbar.c'; else $(CYGPATH_W) '$(srcdir)/progressbar/src/progressbar.c'; fi`
	$(AM_V_at)$(am__mv) progressbar/src/$(DEPDIR)/rotor-progressbar.Tpo progressbar/src/$(DEPDIR)/rotor-progressbar.Po
#	$(AM_V_CC)source='progressbar/src/progressbar.c' object='progressbar/src/rotor-progressbar.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o progressbar/src/rotor-progressbar.obj `if test -f 'progressbar/src/progressbar.c'; then $(CYGPATH_W) 'progressbar/src/progressbar.c'; else $(CYGPATH_W) '$(srcdir)/progressbar/src/progressbar.c'; fi`

passwdqc-1.3.1/rotor-passwdqc_parse.o: passwdqc-1.3.1/passwdqc_parse.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_parse.o -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_parse.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_parse.o `test -f 'passwdqc-1.3.1/passwdqc_parse.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_parse.c
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_parse.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_parse.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_parse.c' object='passwdqc-1.3.1/rotor-passwdqc_parse.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_parse.o `test -f 'passwdqc-1.3.1/passwdqc_parse.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_parse.c

passwdqc-1.3.1/rotor-passwdqc_parse.obj: passwdqc-1.3.1/passwdqc_parse.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_parse.obj -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_parse.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_parse.obj `if test -f 'passwdqc-1.3.1/passwdqc_parse.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_parse.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_parse.c'; fi`
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_parse.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_parse.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_parse.c' object='passwdqc-1.3.1/rotor-passwdqc_parse.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_parse.obj `if test -f 'passwdqc-1.3.1/passwdqc_parse.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_parse.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_parse.c'; fi`

passwdqc-1.3.1/rotor-passwdqc_memzero.o: passwdqc-1.3.1/passwdqc_memzero.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_memzero.o -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_memzero.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_memzero.o `test -f 'passwdqc-1.3.1/passwdqc_memzero.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_memzero.c
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_memzero.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_memzero.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_memzero.c' object='passwdqc-1.3.1/rotor-passwdqc_memzero.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_memzero.o `test -f 'passwdqc-1.3.1/passwdqc_memzero.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_memzero.c

passwdqc-1.3.1/rotor-passwdqc_memzero.obj: passwdqc-1.3.1/passwdqc_memzero.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_memzero.obj -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_memzero.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_memzero.obj `if test -f 'passwdqc-1.3.1/passwdqc_memzero.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_memzero.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_memzero.c'; fi`
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_memzero.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_memzero.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_memzero.c' object='passwdqc-1.3.1/rotor-passwdqc_memzero.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_memzero.obj `if test -f 'passwdqc-1.3.1/passwdqc_memzero.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_memzero.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_memzero.c'; fi`

passwdqc-1.3.1/rotor-concat.o: passwdqc-1.3.1/concat.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-concat.o -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-concat.Tpo -c -o passwdqc-1.3.1/rotor-concat.o `test -f 'passwdqc-1.3.1/concat.c' || echo '$(srcdir)/'`passwdqc-1.3.1/concat.c
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-concat.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-concat.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/concat.c' object='passwdqc-1.3.1/rotor-concat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-concat.o `test -f 'passwdqc-1.3.1/concat.c' || echo '$(srcdir)/'`passwdqc-1.3.1/concat.c

passwdqc-1.3.1/rotor-concat.obj: passwdqc-1.3.1/concat.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-concat.obj -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-concat.Tpo -c -o passwdqc-1.3.1/rotor-concat.obj `if test -f 'passwdqc-1.3.1/concat.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/concat.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/concat.c'; fi`
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-concat.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-concat.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/concat.c' object='passwdqc-1.3.1/rotor-concat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-concat.obj `if test -f 'passwdqc-1.3.1/concat.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/concat.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/concat.c'; fi`

passwdqc-1.3.1/rotor-passwdqc_check.o: passwdqc-1.3.1/passwdqc_check.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_check.o -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_check.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_check.o `test -f 'passwdqc-1.3.1/passwdqc_check.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_check.c
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_check.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_check.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_check.c' object='passwdqc-1.3.1/rotor-passwdqc_check.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_check.o `test -f 'passwdqc-1.3.1/passwdqc_check.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_check.c

passwdqc-1.3.1/rotor-passwdqc_check.obj: passwdqc-1.3.1/passwdqc_check.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_check.obj -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_check.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_check.obj `if test -f 'passwdqc-1.3.1/passwdqc_check.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_check.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_check.c'; fi`
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_check.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_check.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_check.c' object='passwdqc-1.3.1/rotor-passwdqc_check.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_check.obj `if test -f 'passwdqc-1.3.1/passwdqc_check.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_check.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_check.c'; fi`

passwdqc-1.3.1/rotor-passwdqc_load.o: passwdqc-1.3.1/passwdqc_load.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_load.o -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_load.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_load.o `test -f 'passwdqc-1.3.1/passwdqc_load.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_load.c
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_load.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_load.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_load.c' object='passwdqc-1.3.1/rotor-passwdqc_load.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_load.o `test -f 'passwdqc-1.3.1/passwdqc_load.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_load.c

passwdqc-1.3.1/rotor-passwdqc_load.obj: passwdqc-1.3.1/passwdqc_load.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_load.obj -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_load.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_load.obj `if test -f 'passwdqc-1.3.1/passwdqc_load.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_load.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_load.c'; fi`
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_load.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_load.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_load.c' object='passwdqc-1.3.1/rotor-passwdqc_load.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_load.obj `if test -f 'passwdqc-1.3.1/passwdqc_load.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_load.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_load.c'; fi`

passwdqc-1.3.1/rotor-passwdqc_random.o: passwdqc-1.3.1/passwdqc_random.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_random.o -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_random.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_random.o `test -f 'passwdqc-1.3.1/passwdqc_random.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_random.c
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_random.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_random.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_random.c' object='passwdqc-1.3.1/rotor-passwdqc_random.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_random.o `test -f 'passwdqc-1.3.1/passwdqc_random.c' || echo '$(srcdir)/'`passwdqc-1.3.1/passwdqc_random.c

passwdqc-1.3.1/rotor-passwdqc_random.obj: passwdqc-1.3.1/passwdqc_random.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-passwdqc_random.obj -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_random.Tpo -c -o passwdqc-1.3.1/rotor-passwdqc_random.obj `if test -f 'passwdqc-1.3.1/passwdqc_random.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_random.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_random.c'; fi`
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_random.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-passwdqc_random.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/passwdqc_random.c' object='passwdqc-1.3.1/rotor-passwdqc_random.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-passwdqc_random.obj `if test -f 'passwdqc-1.3.1/passwdqc_random.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/passwdqc_random.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/passwdqc_random.c'; fi`

passwdqc-1.3.1/rotor-wordset_4k.o: passwdqc-1.3.1/wordset_4k.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-wordset_4k.o -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-wordset_4k.Tpo -c -o passwdqc-1.3.1/rotor-wordset_4k.o `test -f 'passwdqc-1.3.1/wordset_4k.c' || echo '$(srcdir)/'`passwdqc-1.3.1/wordset_4k.c
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-wordset_4k.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-wordset_4k.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/wordset_4k.c' object='passwdqc-1.3.1/rotor-wordset_4k.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-wordset_4k.o `test -f 'passwdqc-1.3.1/wordset_4k.c' || echo '$(srcdir)/'`passwdqc-1.3.1/wordset_4k.c

passwdqc-1.3.1/rotor-wordset_4k.obj: passwdqc-1.3.1/wordset_4k.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -MT passwdqc-1.3.1/rotor-wordset_4k.obj -MD -MP -MF passwdqc-1.3.1/$(DEPDIR)/rotor-wordset_4k.Tpo -c -o passwdqc-1.3.1/rotor-wordset_4k.obj `if test -f 'passwdqc-1.3.1/wordset_4k.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/wordset_4k.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/wordset_4k.c'; fi`
	$(AM_V_at)$(am__mv) passwdqc-1.3.1/$(DEPDIR)/rotor-wordset_4k.Tpo passwdqc-1.3.1/$(DEPDIR)/rotor-wordset_4k.Po
#	$(AM_V_CC)source='passwdqc-1.3.1/wordset_4k.c' object='passwdqc-1.3.1/rotor-wordset_4k.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(rotor_CFLAGS) $(CFLAGS) -c -o passwdqc-1.3.1/rotor-wordset_4k.obj `if test -f 'passwdqc-1.3.1/wordset_4k.c'; then $(CYGPATH_W) 'passwdqc-1.3.1/wordset_4k.c'; else $(CYGPATH_W) '$(srcdir)/passwdqc-1.3.1/wordset_4k.c'; fi`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f libntru/src/$(DEPDIR)/$(am__dirstamp)
	-rm -f libntru/src/$(am__dirstamp)
	-rm -f passwdqc-1.3.1/$(DEPDIR)/$(am__dirstamp)
	-rm -f passwdqc-1.3.1/$(am__dirstamp)
	-rm -f progressbar/src/$(DEPDIR)/$(am__dirstamp)
	-rm -f progressbar/src/$(am__dirstamp)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f zefcrypt/$(DEPDIR)/$(am__dirstamp)
	-rm -f zefcrypt/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf libntru/src/$(DEPDIR) passwdqc-1.3.1/$(DEPDIR) progressbar/src/$(DEPDIR) src/$(DEPDIR) zefcrypt/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf libntru/src/$(DEPDIR) passwdqc-1.3.1/$(DEPDIR) progressbar/src/$(DEPDIR) src/$(DEPDIR) zefcrypt/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
